//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDSampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContactDetail
    {
        public tblContactDetail()
        {
            this.tblStudents = new HashSet<tblStudent>();
        }
    
        public int ContactId { get; set; }
        public string ContactDetail { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<tblStudent> tblStudents { get; set; }
    }
}
