//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDSampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCatalogType
    {
        public tblCatalogType()
        {
            this.tblCatalogs = new HashSet<tblCatalog>();
        }
    
        public int TypeId { get; set; }
        public string TypeName { get; set; }
    
        public virtual ICollection<tblCatalog> tblCatalogs { get; set; }
    }
}
